/**
 * Custom-request flow — UI-driven E2E.
 *
 * v1 of this spec posted straight to `/api/bookings/custom-request` and never
 * touched the form. v2 (the modal + 3-step flow: Step1Shape → Step2Details →
 * Step3Review) is the whole point of this rewrite: drive the real DOM.
 *
 * Five scenarios:
 *   A) Single event, full happy path through the modal, ending on "Request sent".
 *   B) Multi-day (3 events) — fills all three per-day cards via data-testid
 *      scoping and reaches Step 3.
 *   C) Ordering guard — re-picking an earlier event's date to *after* a later
 *      event's date clears the later one (Step2Details' ascending-date
 *      invariant).
 *   D) Guest-count field allows clearing the seeded "50" and retyping freely
 *      (regression guard for the old leading-"1" lock bug).
 *   E) Deep-link fallback — `/vendors/[slug]/request` still renders the flow
 *      inline with a "Back to {business_name}" link.
 *
 * Calendar interaction notes:
 * - The DatePicker wraps react-day-picker v10. Each day button's accessible
 *   name is generated by `labelDayButton` as date-fns' locale "PPPP" format
 *   ("EEEE, MMMM do, y", e.g. "Friday, October 3rd, 2025"), with "Today, "
 *   prefixed / ", selected" suffixed when applicable. We reproduce that
 *   formatting locally (see `formatDayLabel`) rather than depending on
 *   `date-fns` directly, since it's only a transitive dependency here.
 * - The "next month" nav button's accessible name is the library's default
 *   "Go to the Next Month" (see react-day-picker's `labelNext`).
 * - To keep dates unambiguous regardless of what day it is when the suite
 *   runs, every scenario navigates one calendar month forward and picks a
 *   day-of-month via `pickCalendarDate`, scoped to the `data-testid` added to
 *   Step2Details in this same PR (`event-card-${idx}` / `date-picker-${idx}`).
 */

import { test, expect, type Locator, type Page } from '@playwright/test';
import { seedCouple, seedVendor, cleanup, type TestUser, type TestVendor } from './helpers/seed';
import { loginAs } from './helpers/login';

// ---------------------------------------------------------------------------
// Date helpers — mirror react-day-picker's default "PPPP" day-button label.
// ---------------------------------------------------------------------------

function ordinal(n: number): string {
  const j = n % 10;
  const k = n % 100;
  if (j === 1 && k !== 11) return `${n}st`;
  if (j === 2 && k !== 12) return `${n}nd`;
  if (j === 3 && k !== 13) return `${n}rd`;
  return `${n}th`;
}

/** Reproduces date-fns' en-US "PPPP" format: "EEEE, MMMM do, y". */
function formatDayLabel(date: Date): string {
  const weekday = date.toLocaleDateString('en-US', { weekday: 'long' });
  const month = date.toLocaleDateString('en-US', { month: 'long' });
  const year = date.getFullYear();
  return `${weekday}, ${month} ${ordinal(date.getDate())}, ${year}`;
}

/**
 * A future date `monthsAhead` calendar months from today, on `dayOfMonth`.
 * Clamps via setDate(1) first so month-end overflow (e.g. Jan 31 + 1 month)
 * never rolls into an unexpected month.
 */
function futureDate(monthsAhead: number, dayOfMonth: number): Date {
  const d = new Date();
  d.setDate(1);
  d.setMonth(d.getMonth() + monthsAhead);
  d.setDate(dayOfMonth);
  return d;
}

/** Clicks the DatePicker's "next month" nav `monthsAhead` times, then the target day. */
async function pickCalendarDate(scope: Locator, monthsAhead: number, dayOfMonth: number) {
  for (let i = 0; i < monthsAhead; i++) {
    await scope.getByRole('button', { name: /go to the next month/i }).click();
  }
  const date = futureDate(monthsAhead, dayOfMonth);
  await scope.getByRole('button', { name: formatDayLabel(date) }).click();
  return date;
}

// ---------------------------------------------------------------------------
// Shared setup
// ---------------------------------------------------------------------------

/**
 * Opens the vendor page and clicks the "Request a quote" CTA to open the modal on Step 1.
 *
 * The vendor page always renders a virtual "Custom Request" tile inside the
 * PackageGrid (see `appendCustomRequest` — it's unconditionally appended, so
 * `packages.length > 0` is always true and the "Choose your package" branch
 * always renders, even for a vendor with zero real packages). That tile is
 * also an `<a role="link">` whose accessible name contains "Request a quote",
 * but clicking it does a plain Next.js navigation to `/vendors/[slug]/request`
 * rather than opening the modal (`onClick` there has no `setCustomRequestOpen`
 * wiring). The one link that *does* open the modal is the "Don't see what you
 * need? Request a quote →" text link — it's the only "Request a quote" link
 * whose accessible name ends with the literal arrow glyph, so we anchor on
 * that to avoid ambiguity.
 */
async function openModalFromVendorPage(page: Page, vendorSlug: string) {
  await page.goto(`/vendors/${vendorSlug}`);
  await page
    .getByRole('link', { name: /request a quote →/i })
    .first()
    .click();
  await expect(
    page.getByRole('heading', { name: /what.s the shape of your event/i })
  ).toBeVisible();
}

test.describe('Custom-request flow — UI-driven', () => {
  let couple: TestUser | null = null;
  let vendor: TestVendor | null = null;

  test.afterEach(async () => {
    await cleanup(couple, vendor);
    couple = null;
    vendor = null;
  });

  test('A) single event through the modal', async ({ browser }) => {
    test.setTimeout(90_000);
    couple = await seedCouple({ markOnboardingComplete: true });
    vendor = await seedVendor({ publish: true });

    const ctx = await browser.newContext();
    const page = await ctx.newPage();
    await loginAs(page, couple);

    await openModalFromVendorPage(page, vendor.vendorSlug);

    // Step 1 — single event is the default shape; continue.
    await page.getByRole('radio', { name: /single event/i }).check();
    await page.getByRole('button', { name: /continue/i }).click();

    // Step 2
    await expect(page.getByRole('heading', { name: /tell us the details/i })).toBeVisible();
    const card = page.getByTestId('event-card-0');
    await pickCalendarDate(page.getByTestId('date-picker-0'), 1, 10);

    await page.getByLabel(/start time/i).fill('16:00');
    // `.fill()` rather than click+Control+A+type: simulating the select-all
    // keystroke raced with React's controlled re-render often enough in CI
    // to leave stray digits from the seeded '50' behind (e.g. "25050").
    await page.getByLabel(/guests/i).fill('250');

    await card.locator('button[role="combobox"]').click();
    await page.getByRole('option', { name: 'Wedding / Shaadi' }).click();

    await page.getByLabel(/event city/i).fill('Houston, TX');
    await page.getByLabel(/venue name/i).fill('The Post Oak Hotel');
    await page.getByRole('radio', { name: /15k.30k/i }).click();
    await page
      .getByPlaceholder(/tell the vendor/i)
      .fill(
        'Traditional South Asian wedding, ceremony at 5, reception dinner + dance floor. Would love drone shots.'
      );

    await page.getByRole('button', { name: /^review/i }).click();

    // Step 3
    await expect(page.getByRole('heading', { name: /review and send/i })).toBeVisible();
    await expect(page.getByText(/houston, tx/i).first()).toBeVisible();
    await expect(page.getByText(/\$15k.30k/i).first()).toBeVisible();
    await page.getByRole('button', { name: /^send request$/i }).click();

    await expect(page.getByRole('heading', { name: /request sent/i })).toBeVisible();

    await ctx.close();
  });

  test('B) multi-day 3 events through the modal', async ({ browser }) => {
    test.setTimeout(90_000);
    couple = await seedCouple({ markOnboardingComplete: true });
    vendor = await seedVendor({ publish: true });

    const ctx = await browser.newContext();
    const page = await ctx.newPage();
    await loginAs(page, couple);

    await openModalFromVendorPage(page, vendor.vendorSlug);

    await page.getByRole('radio', { name: /multi-day/i }).check();
    await page.getByLabel(/how many events/i).fill('3');
    await page.getByRole('button', { name: /continue/i }).click();

    // Three per-day cards rendered.
    await expect(page.getByTestId('event-card-0')).toBeVisible();
    await expect(page.getByTestId('event-card-1')).toBeVisible();
    await expect(page.getByTestId('event-card-2')).toBeVisible();

    // Ascending dates in the same future month (5th, 15th, 25th) — each
    // DatePicker instance navigates independently, one month forward.
    await pickCalendarDate(page.getByTestId('date-picker-0'), 1, 5);
    await pickCalendarDate(page.getByTestId('date-picker-1'), 1, 15);
    await pickCalendarDate(page.getByTestId('date-picker-2'), 1, 25);

    // Event type + guest count keep their seeded defaults ('wedding' / '50'),
    // which already satisfy Step2's canContinue check — only city + a long
    // enough description are required beyond the three dates.
    await page.getByLabel(/event city/i).fill('Chicago, IL');
    await page
      .getByPlaceholder(/tell the vendor/i)
      .fill(
        'Three-day wedding weekend: mehndi Friday, wedding Saturday, walima Sunday. Please quote the whole weekend as a bundle.'
      );

    await page.getByRole('button', { name: /^review/i }).click();

    await expect(page.getByRole('heading', { name: /review and send/i })).toBeVisible();
    await expect(page.getByText(/3-day event/i)).toBeVisible();

    await ctx.close();
  });

  test('C) picking an earlier event date after a later one clears the later date', async ({
    browser,
  }) => {
    test.setTimeout(90_000);
    couple = await seedCouple({ markOnboardingComplete: true });
    vendor = await seedVendor({ publish: true });

    const ctx = await browser.newContext();
    const page = await ctx.newPage();
    await loginAs(page, couple);

    await openModalFromVendorPage(page, vendor.vendorSlug);

    await page.getByRole('radio', { name: /multi-day/i }).check();
    await page.getByLabel(/how many events/i).fill('2');
    await page.getByRole('button', { name: /continue/i }).click();

    const day1Picker = page.getByTestId('date-picker-0');
    const day2Picker = page.getByTestId('date-picker-1');

    // Day 1 = 5th, Day 2 = 15th of the same future month — ascending, allowed.
    await pickCalendarDate(day1Picker, 1, 5);
    const day2Date = await pickCalendarDate(day2Picker, 1, 15);

    // Day 2's picked day-of-month button should now read as selected.
    await expect(
      day2Picker.getByRole('button', { name: `${formatDayLabel(day2Date)}, selected` })
    ).toBeVisible();

    // Re-pick Day 1 to the 20th — after Day 2's 15th. Both pickers are still
    // showing the same (already-navigated) future month, so no further month
    // navigation is needed.
    await day1Picker.getByRole('button', { name: formatDayLabel(futureDate(1, 20)) }).click();

    // Ascending-date invariant (Step2Details.updateEvent) should have cleared
    // Day 2's date: its 15th button must no longer carry the ", selected" suffix.
    await expect(
      day2Picker.getByRole('button', { name: `${formatDayLabel(day2Date)}, selected` })
    ).toHaveCount(0);
    // The "must be after" hint for Day 2 should reflect the new Day 1 date.
    await expect(page.getByText(/must be after/i)).toBeVisible();

    await ctx.close();
  });

  test('D) guest count field allows clearing the seeded default and retyping', async ({
    browser,
  }) => {
    test.setTimeout(90_000);
    couple = await seedCouple({ markOnboardingComplete: true });
    vendor = await seedVendor({ publish: true });

    const ctx = await browser.newContext();
    const page = await ctx.newPage();
    await loginAs(page, couple);

    await openModalFromVendorPage(page, vendor.vendorSlug);

    await page.getByRole('radio', { name: /single event/i }).check();
    await page.getByRole('button', { name: /continue/i }).click();

    const guests = page.getByLabel(/guests/i);
    // Field starts at the seeded default '50'. Clear it, retype '600'.
    await expect(guests).toHaveValue('50');
    // `.fill()` clears + sets the value in one action — more reliable in CI
    // than simulating Control+A/Delete keystrokes, which raced with React's
    // controlled-input re-render in this input often enough to flake
    // (observed "6000" instead of "600" from a dropped delete). The behavior
    // under test — that the field accepts an arbitrary new value instead of
    // clamping back to a leading "1" — doesn't depend on *how* the clear
    // happens.
    await guests.fill('600');
    await expect(guests).toHaveValue('600');
    // Also exercise real keystrokes on top of the cleared field, to cover the
    // original bug's actual trigger path (typing digit-by-digit into an
    // empty/short field).
    await guests.fill('');
    await guests.type('42');
    await expect(guests).toHaveValue('42');

    await ctx.close();
  });

  test('E) /vendors/[slug]/request renders as a page with a back link', async ({ browser }) => {
    test.setTimeout(90_000);
    couple = await seedCouple({ markOnboardingComplete: true });
    vendor = await seedVendor({ publish: true });

    const ctx = await browser.newContext();
    const page = await ctx.newPage();
    await loginAs(page, couple);

    await page.goto(`/vendors/${vendor.vendorSlug}/request`);
    await expect(page.getByRole('link', { name: /back to/i })).toBeVisible();
    await expect(
      page.getByRole('heading', { name: /what.s the shape of your event/i })
    ).toBeVisible();

    await ctx.close();
  });
});
